Add support for specifying a predicate to find a specific element
sindresorhus/element-ready pull request #38
Opened 2021-10-03 19:17 UTC by bengry

fixes #37

2021-10-04 06:05 UTC, sindresorhus requested changes

2021-10-04 06:05 UTC, sindresorhus commented on index.js
> +	predicate = () => true,
It's wasteful to execute an empty function for each element.

2021-10-04 06:05 UTC, sindresorhus commented on index.d.ts
> +	/**
This needs a description (including mentioning its use-cases), and ideally a realistic code example.

2021-10-04 06:05 UTC, sindresorhus commented
This will need readme updates and tests.

2021-10-04 06:05 UTC, sindresorhus commented
It should also be added to `observeReadyElements`.

2021-10-04 07:00 UTC, bengry commented
> This will need readme updates and tests.

I added this to the readme, but I can't run the tests locally since it seems like the `typescript` package is missing from `devDependencies`. Is that on purpose? I'm not sure how they pass in CI.

> It should also be added to `observeReadyElements`.

Done

2021-10-04 07:01 UTC, bengry commented
On an unrelated note, is there a reason to maintain a separate `.d.ts` file, instead of re-writing the package in TypeScript? It's not large and a re-write should be simple enough.

2021-10-04 07:23 UTC, sindresorhus commented
> On an unrelated note, is there a reason to maintain a separate .d.ts file, instead of re-writing the package in TypeScript?

Yes. I don't like TS. I only provide types for user convenience. (https://github.com/sindresorhus/ky/issues/321#issuecomment-765594679)

2021-10-04 08:39 UTC, sindresorhus requested changes

2021-10-04 08:39 UTC, sindresorhus commented on readme.md
> +If defined, the predicate will be called for each element that matches the selector. If it returns `true`, the element will be returned.
```suggestion
A predicate function will be called for each element that matches the selector. If it returns `true`, the element will be returned.
```

2021-10-04 08:39 UTC, sindresorhus commented on index.d.ts
> +	@example
The example is missing the JS part, like in your issue.

And this example also needs to be added to the readme.

Generally, I try to keep index.d.ts and readme in sync as much as possible.

2021-10-04 08:39 UTC, sindresorhus commented on index.js
> +		return element;
```suggestion
		return [...elements].find(element => predicate(element));
```

2021-10-04 08:54 UTC, sindresorhus commented on index.d.ts
> + 	If defined, the predicate will be called for each element that matches the selector. If it returns `true`, the element will be returned.
Readme and index.d.ts should be in sync.

2021-10-04 08:54 UTC, sindresorhus commented on index.d.ts
> +	For example, if the content is dynamic or a selector can't be specific enough - you can check the `.textContent` of each element and only match the one that has the required text.
Readme and index.d.ts should be in sync.

2021-10-04 08:55 UTC, sindresorhus commented on index.d.ts
> +	For example, if the content is dynamic or a selector can't be specific enough - you can check the `.textContent` of each element and only match the one that has the required text.
```suggestion
	For example, if the content is dynamic or a selector cannot be specific enough, you could check `.textContent` of each element and only match the one that has the required text.
```

2021-10-04 09:15 UTC, sindresorhus commented
You overwrote my changes: https://github.com/sindresorhus/element-ready/compare/8dc7b0c24363479246a6a2b4b3cf3d6da6f968c4..ed957e569374df606507811648b6f2730b983a2c

2021-10-04 09:15 UTC, sindresorhus commented
Generally, don't force push in pull requests, it also makes it harder to review what changed.

2021-10-04 09:22 UTC, bengry commented
> You overwrote my changes: [`8dc7b0c24363479246a6a2b4b3cf3d6da6f968c4..ed957e569374df606507811648b6f2730b983a2c` (compare)](https://github.com/sindresorhus/element-ready/compare/8dc7b0c24363479246a6a2b4b3cf3d6da6f968c4..ed957e569374df606507811648b6f2730b983a2c)

I've re-added them in add7485. If I understood correctly - with the last push all that was overridden was the missing `import elementReady from 'element-ready';` from the docs. Since there were both this and the suggestions (which I've implemented separately) in the diffs.

Please LMK if I missed anything.

2021-10-04 09:31 UTC, sindresorhus commented
There were a few other changes too. Just look at the diff I commented.

2021-10-04 09:51 UTC, bengry commented
> There were a few other changes too. Just look at the diff I commented.

Right, but there were also the [suggestion](https://github.com/sindresorhus/element-ready/pull/38#discussion_r721166796), so I think that together we're all aligned now: https://github.com/sindresorhus/element-ready/compare/8dc7b0c24363479246a6a2b4b3cf3d6da6f968c4..add7485

2021-10-04 10:45 UTC, sindresorhus commented
I committed some small tweaks.

2021-10-04 10:46 UTC, sindresorhus commented
The "check elements against a predicate" test is failing though.

2021-10-04 10:54 UTC, bengry commented
> The "check elements against a predicate" test is failing though.

Fixed in cd1f75a. There were some errors due to some renaming I did while working on the tests, and using a non-existent property on the element in the assertion. Funnily enough, these errors would've been caught by TypeScript.

2021-10-05 04:51 UTC, merged

2021-10-05 04:51 UTC, sindresorhus commented
Thanks :)